import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

async function runManual(task, repoDir, context) {
  const artifactsDir = join(repoDir, "usc", "artifacts");
  mkdirSync(artifactsDir, { recursive: true });

  const artifactPath = join(artifactsDir, `${task.id}-instructions.md`);
  const content = `# Execution Instructions: ${task.title}

**Task ID:** ${task.id}  
**Repo:** ${repoDir}  
**Claimant:** ${(task.claim && task.claim.claimant) || "unknown"}

## Transformation

${task.transformation}

## Evidence Requirement

${task.evidence_requirement}

## Review Predicate

${task.review_predicate}

## Steps

1. Perform the transformation described above.
2. Produce evidence that satisfies the evidence requirement.
3. Verify the evidence meets the review predicate.
4. Run \`usc complete --target ${repoDir} --task ${task.id} --result <artifact-path> --reviewer <reviewer-id>\`.

---

*Generated by the manual executor. This is an instruction artifact, not a product code change.*
`;

  writeFileSync(artifactPath, content);

  return {
    artifactPath,
    exitCode: 0,
    stdout: `Wrote execution instructions to ${artifactPath}`,
    stderr: "",
  };
}

export { runManual };
